"""Figure D1: α sweep for HCCP Mondrian vs class-cond vs homoscedastic.

Produces a 2-panel figure (Mendelian, Complex) showing empirical coverage vs α
and σ̂-bin range vs α. Data from outputs/conformal_hetero/*_mondrian/.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# --- Unified NeurIPS-classic style ---
import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from T_tools.paper_style import apply_paper_style  # noqa: E402
apply_paper_style()


def load_sweeps(path: Path) -> dict:
    d = json.load(open(path))
    return {
        "hetero": d.get("alpha_sweep_hetero", {}),
        "homosc": d.get("alpha_sweep_homosc", {}),
        "mondrian": d.get("alpha_sweep_mondrian", {}),
    }


def plot(ax, sweeps: dict, ds_name: str) -> None:
    alphas_str = sorted(sweeps["mondrian"].keys(), key=float)
    alphas = [float(a) for a in alphas_str]

    # panel: coverage vs 1-α target
    for label, key, marker, color in [
        ("Split CP (class-cond, homoscedastic)", "homosc", "o", "#888888"),
        ("HCCP class-cond (Eq.~3 score)",        "hetero", "s", "#4477aa"),
        ("HCCP Mondrian (y×σ̂-bin), K=5",         "mondrian", "D", "#cc3311"),
    ]:
        sweep = sweeps[key]
        if not sweep:
            continue
        cov = [sweep[a]["coverage"] for a in alphas_str]
        ax.plot(alphas, cov, marker=marker, color=color, label=label, lw=1.8,
                markersize=7, markerfacecolor="white", markeredgewidth=1.8)

    # reference y = 1 - α
    ax.plot(alphas, [1 - a for a in alphas], ls="--", color="#444444",
            lw=1.2, label=r"target $1-\alpha$", zorder=0)

    ax.set_xlabel(r"miscoverage $\alpha$")
    ax.set_ylabel("empirical coverage")
    ax.set_title(f"{ds_name} (CADD+GPN-MSA+Borzoi)")
    ax.grid(ls="--", lw=0.3, alpha=0.4)
    ax.set_xlim(-0.02, 0.55)
    ax.set_ylim(0.40, 1.02)
    ax.legend(fontsize=8, loc="lower left", frameon=True, framealpha=0.9)


def plot_sigma_range(ax, sweeps: dict, ds_name: str) -> None:
    alphas_str = sorted(sweeps["mondrian"].keys(), key=float)
    alphas = [float(a) for a in alphas_str]
    mon = sweeps["mondrian"]
    rng = [mon[a]["sigma_cov_range"] for a in alphas_str]
    ax.bar(alphas, rng, width=0.03, color="#cc3311", alpha=0.8,
           label="HCCP Mondrian σ̂-bin coverage range")
    ax.axhline(0.04, color="#444", ls="--", lw=1, label="paper headline 0.04")
    ax.set_xlabel(r"miscoverage $\alpha$")
    ax.set_ylabel(r"$\max_b \mathrm{cov}_b - \min_b \mathrm{cov}_b$")
    ax.set_title(f"σ̂-bin gap vs α — {ds_name}")
    ax.grid(ls="--", lw=0.3, alpha=0.4)
    ax.set_xlim(-0.02, 0.55)
    ax.set_ylim(0, max(max(rng), 0.08) * 1.2)
    ax.legend(fontsize=8, loc="upper left", frameon=True, framealpha=0.9)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mendelian-results",
                    default="outputs/conformal_hetero/CADD+GPN-MSA+Borzoi_mendelian_abs_mondrian/conformal_hetero_results.json")
    ap.add_argument("--complex-results",
                    default="outputs/conformal_hetero/CADD+GPN-MSA+Borzoi_complex_abs_mondrian/conformal_hetero_results.json")
    ap.add_argument("--out",
                    default="papers/neurips2027_pathA/figures/figD_alpha_sweep.pdf")
    args = ap.parse_args()

    mend = load_sweeps(Path(args.mendelian_results))
    comp = load_sweeps(Path(args.complex_results))

    fig, axes = plt.subplots(2, 2, figsize=(10, 7.5))
    plot(axes[0, 0], mend, "Mendelian")
    plot(axes[0, 1], comp, "Complex")
    plot_sigma_range(axes[1, 0], mend, "Mendelian")
    plot_sigma_range(axes[1, 1], comp, "Complex")
    fig.suptitle(r"HCCP α sweep on TraitGym — coverage and $\hat\sigma$-bin gap",
                 fontsize=11, y=1.00)
    fig.tight_layout()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out, bbox_inches="tight", dpi=200)
    fig.savefig(out.with_suffix(".png"), bbox_inches="tight", dpi=200)
    print(f"saved: {out}, {out.with_suffix('.png')}")

    # Also emit a LaTeX-ready table
    tbl_path = out.parent / "figD_alpha_sweep_table.tex"
    with open(tbl_path, "w") as f:
        f.write("% Auto-generated by scripts/28_alpha_sweep_figure.py\n")
        f.write("\\begin{tabular}{rrrrrr}\n\\toprule\n")
        f.write("$\\alpha$ & M cov & M $\\hat\\sigma$-gap & C cov & C $\\hat\\sigma$-gap & singleton (M / C)\\\\\n")
        f.write("\\midrule\n")
        alphas_str = sorted(mend["mondrian"].keys(), key=float)
        for a in alphas_str:
            mm = mend["mondrian"][a]
            cc = comp["mondrian"][a]
            f.write(f"{float(a):.2f} & {mm['coverage']:.3f} & {mm['sigma_cov_range']:.3f} & "
                    f"{cc['coverage']:.3f} & {cc['sigma_cov_range']:.3f} & "
                    f"{mm['frac_singleton']*100:.0f}\\% / {cc['frac_singleton']*100:.0f}\\% \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")
    print(f"saved: {tbl_path}")


if __name__ == "__main__":
    main()
